version: '3.9'

services:
  postgres:
    image: postgres:11.5
    container_name: 'postgres'
    hostname: 'postgres'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: postgres
  #  volumes:
  #    - './postgres:/docker-entrypoint-initdb.d'
  #    - './postgres/sql-files:/sql-files'